FROM node:16.16.0-slim

WORKDIR /app

COPY bundles-src/ /app/bundles-src
COPY package.json /app/
RUN npm install --include=dev
CMD ["./node_modules/.bin/parcel", "watch", "bundles-src/index.js", "--dist-dir", "bundles", "--public-url", "./"]
