FROM node:16.16.0-slim as builder

WORKDIR /app

COPY bundles-src/ /app/bundles-src
COPY package.json /app/

RUN npm install --include=dev

RUN npx parcel build bundles-src/index.js --dist-dir bundles --public-url="./"

FROM node:16.16.0-alpine

WORKDIR /app

COPY --from=builder /app/bundles /app/bundles

CMD ["sh", "-c", "mkdir -p /out && cp -r /app/bundles/. /out/"]
