# Generated by Django 5.2.7 on 2025-11-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0002_geocodedaddress_fetched_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geocodedaddress',
            name='fetched_at',
        ),
        migrations.RemoveField(
            model_name='geocodedaddress',
            name='norm_address',
        ),
        migrations.AlterField(
            model_name='geocodedaddress',
            name='address',
            field=models.CharField(db_index=True, max_length=512, unique=True, verbose_name='Адрес'),
        ),
    ]
