# Generated by Django 5.2.7 on 2025-10-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodedaddress',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время получения координат'),
        ),
    ]
