# Generated by Django 5.2.7 on 2025-10-20 17:45

import django.core.validators
from django.apps.registry import Apps
from django.db import migrations, models


def populate_old_items_prices(apps: Apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    order_items = OrderItem.objects.all().iterator()

    for order_item in order_items:
        if not order_item.price and order_item.product:
            order_item.price = order_item.product.price
            order_item.save(update_fields=['price'])


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0041_rename_first_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8,
                                      validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_old_items_prices,
            reverse_code=migrations.RunPython.noop,
        )
    ]
