# Generated by Django 5.2.7 on 2025-10-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Оплата онлайн'), ('cash', 'Наличными курьеру'), ('card', 'Банковской картой курьеру')], db_index=True, default='cash', max_length=8),
        ),
    ]
