# Generated by Django 5.2.7 on 2025-11-01 14:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Оплата онлайн'), ('cash', 'Наличными курьеру'), ('card', 'Банковской картой курьеру')], db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Мобильный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Не обработан'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('ready_for_pickup', 'Готов к выдаче'), ('in_delivery', 'В пути'), ('delivered', 'Доставлен')], db_index=True, default='not_processed', max_length=16, verbose_name='Статус'),
        ),
    ]
