# Generated by Django 5.2.7 on 2025-10-15 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_productitem_orderproductitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
