# Generated by Django 5.2.7 on 2025-10-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('confirmed', 'Подтвержден'), ('ready_for_pickup', 'Готов к выдаче'), ('in_delivery', 'В пути'), ('delivered', 'Доставлен')], db_index=True, default='accepted', max_length=16, verbose_name='Статус'),
        ),
    ]
